### ISSUE TITLE
Enable automated logging

### ISSUE THREAD

**Issue by MiguelRodo** [SATVILab/UtilsReportRSV#1]
### Tasks

- [ ] Automatically extract log files into appendix in report
- [ ] Automatically add a log file when you save a plot
- [ ] Automatically add a log file when you copy a file
